FROM --platform=$BUILDPLATFORM tonistiigi/xx AS xx
FROM --platform=$BUILDPLATFORM golang:1.20-alpine
LABEL org.opencontainers.image.source=https://github.com/IzumaNetworks/test-hello-world
LABEL org.opencontainers.image.description="Hello World Go test container"
LABEL org.opencontainers.image.licenses=Apache-2.0

# get xx tools to build image
RUN apk add clang lld
COPY --from=xx / /
ADD app /app
ARG TARGETPLATFORM
RUN xx-apk add musl-dev gcc
ENV CGO_ENABLED=1
WORKDIR /app
# RUN gcc -dumpmachine
RUN xx-go --wrap
RUN go build -o app . && xx-verify app
ENV HELLO_NAME="World"
ENV HELLO_PORT="8090"
ENTRYPOINT [ "/app/app" ]
CMD []
