FROM --platform=$BUILDPLATFORM golang:1.20 AS build
LABEL org.opencontainers.image.source=https://github.com/IzumaNetworks/test-hello-world
LABEL org.opencontainers.image.description="Hello World Go test container"
LABEL org.opencontainers.image.licenses=Apache-2.0
ADD app /app
ARG TARGETOS TARGETARCH
ENV CGO_ENABLED=0
WORKDIR /app
RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o app .
ENV HELLO_NAME="World"
ENTRYPOINT [ "/app/app" ]
CMD []
