FROM --platform=$BUILDPLATFORM tonistiigi/xx AS xx
FROM --platform=$BUILDPLATFORM golang:1.20
LABEL org.opencontainers.image.source=https://github.com/IzumaNetworks/test-hello-world
LABEL org.opencontainers.image.description="Hello World Go test container"
LABEL org.opencontainers.image.licenses=Apache-2.0

RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential
RUN DEBIAN_FRONTEND=noninteractive apt-get -y clean

COPY --from=xx / /
ADD app /app
ARG TARGETPLATFORM
RUN xx-apt install -y libc6-dev gcc
ENV CGO_ENABLED=1
WORKDIR /app
RUN xx-go --wrap
RUN go build -o app . && xx-verify app
ENV HELLO_NAME="World"
ENTRYPOINT [ "/app/app" ]
CMD []
