FROM --platform=$BUILDPLATFORM golang:1.20 AS build
LABEL org.opencontainers.image.source=https://github.com/IzumaNetworks/test-hello-world
LABEL org.opencontainers.image.description="Hello World Go test container"
LABEL org.opencontainers.image.licenses=Apache-2.0
# get gcc cross toolchain
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install g++-x86-64-linux-gnu libc6-dev-amd64-cross
RUN DEBIAN_FRONTEND=noninteractive apt-get -y clean

ADD app /app
ARG TARGETOS TARGETARCH
ENV CGO_ENABLED=1
WORKDIR /app
# RUN gcc -dumpmachine
RUN CC=x86_64-linux-gnu-gcc GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o app .
ENV HELLO_NAME="World"
ENV HELLO_PORT="8090"
ENTRYPOINT [ "/app/app" ]
CMD []
